- name: mainplay-create or terminate instances
  hosts: local
  connection: local
  vars: 
    image_id: "ami-0220d79f3f480ecf5"
    domain_name: "devarshi.live"
    zone_id: "Z06569691EDOCEFWDOVQV"
    zone_name: "devarshi.live"
    aws_region: "us-east-1"
    instance_action: create
    env: dev
    project: roboshop
    instances: 
      - mongodb 
      - redis
      - rabbitmq 
      - mysql 

      - catalogue 
      - user 
      - cart 
      - shipping 
      - payment 

      - frontend 
  tasks: 
    - name: create ec2 instances
      amazon.aws.ec2_instance:
        name: "{{ item }}-{{ env }}"
        image_id: "{{ image_id }}" 
        instance_type: t3.micro
        security_groups: 
          - sg1

        count: 1

        tags:
          Environment: "{{ env }}"
          Project: "{{ project }}"
          ManagedBy: ansible
          
        state: running 
        wait: true
      loop: "{{ instances }}"
      register: ec2_details
      when: instance_action == "create"

    # terminate instances
    - name: terminate all ec2 instances created 
      amazon.aws.ec2_instance:
        name: "{{ item  }}-{{ env }}"
        state: absent
      loop: "{{ instances }}"
      when: instance_action == "terminate"
  
    # dns records for the created instances - Private IP
    - name: create the DNS records
      amazon.aws.route53:
        zone: "{{ zone_name }}"
        record: "{{ item.item }}-{{ env }}.rb.{{ zone_name }}"
        type: A
        ttl: 1
        value: "{{ item.instances[0].private_ip_address }}"
        state: present

        wait: false
        overwrite: true
      loop: "{{ ec2_details.results | rejectattr('item', 'equalto', 'frontend') | list }}"
      when: instance_action == "create"

    #DNS record for the frontend 
    - name: create the DNS record for the frontend
      amazon.aws.route53:
        zone: "{{ zone_name }}"
        record: "roboshop-{{ env }}.rb.{{ zone_name }}"
        type: A
        ttl: 1
        value: "{{ item.instances[0].public_ip_address }}"
        state: present

        wait: false
        overwrite: true
      loop: "{{ ec2_details.results | selectattr('item', 'equalto', 'frontend') | list }}"
      when: instance_action == "create"

    # delete dns records
    - name: delete dns records
      amazon.aws.route53:
        zone: "{{ zone_name }}"
        record: "{{ item }}-{{ env }}.rb.{{ zone_name }}"
        type: A
        state: absent
      loop: "{{ instances }}"
      when: 
        - instance_action == "terminate"

    # delete record for the frontend 
    - name: delete dns record for the frontend
      amazon.aws.route53:
        zone: "{{ zone_name }}"
        record: "roboshop-{{ env }}.rb.{{ zone_name }}"
        type: A
        ttl: 1

        state: absent
      when: 
        - instance_action == "terminate"
        - "'frontend' in instances"

    # wait for dns resolution
    - name: Wait until DNS record resolves
      ansible.builtin.command:
        cmd: getent hosts {{ item }}-{{ env }}.rb.{{ zone_name }}
      register: dns_check
      retries: 10
      delay: 5
      until: dns_check.rc == 0
      loop: "{{ instances }}"