- name: restart "{{ component }}"
  ansible.builtin.service: 
    name: "{{ component }}"
    state: restarted
  
- name: systemd daemon relaod
  ansible.builtin.systemd_service: 
    daemon_reload: true
