- name: install golang package 
  ansible.builtin.dnf: 
    name: golang  
    state: present
        
- name: Initialize Go module
  ansible.builtin.command:
    cmd: go mod init dispatch
    chdir: /app
    creates: /app/go.mod  

- name: Download Go dependencies
  ansible.builtin.command:
    cmd: go get
    chdir: /app

- name: Build Go application binary
  ansible.builtin.command:
    cmd: go build
    chdir: /app
